% Paper2_Quad_PerceivedDisparity_distance_elevation_ClinicalNotes_072126
% Run perceived-disparity analyses for participants with versus without a
% clinical note, color by clinical-note category, omit stereo-score analyses,
% and formally compare distance/elevation model parameters between groups.

clear;
close all force;
clc;

scriptDir = fileparts(mfilename('fullpath'));
codeDir = fileparts(scriptDir);
addpath(genpath(codeDir));

%% Configuration
quadFileName = 'merged_disparity_0429.csv';
quadFile = fullfile(codeDir, '..', 'QuadExperiments', 'Data', quadFileName);
transformId = 2;
colorMode = "clinicalnotes";
saveLME = true;
removeOutlierParticipants = false;
removeZScoreOutliers = false;
zScoreThreshold = 3;
secondYAxisColor = 'k';
versionLabels = ["Version3", "Version3Lamp5", "Version3Lamp7"];
runConfigs = { ...
    struct('resultsSubdir', 'NoClinicalNote', ...
        'basenameSuffix', '_noClinicalNote', 'hasClinicalNote', false), ...
    struct('resultsSubdir', 'ClinicalNote', ...
        'basenameSuffix', '_withClinicalNote', 'hasClinicalNote', true) ...
    };

importOptions = detectImportOptions(quadFile, 'VariableNamingRule', 'modify');
importOptions = setvartype(importOptions, 'ClinicalNotes', 'string');
allQuadDataBase = readtable(quadFile, importOptions);
if ~ismember('Elevation', allQuadDataBase.Properties.VariableNames)
    allQuadDataBase.Elevation = allQuadDataBase.Observer_Elevation;
end
if ~ismember('Distance', allQuadDataBase.Properties.VariableNames)
    allQuadDataBase.Distance = allQuadDataBase.Observer_Distance;
end
[~, quadBasenameBase] = fileparts(quadFileName);
resultsRoot = fullfile(codeDir, '..', 'Paper2Figures', ...
    ['PerceivedDisparityDistanceElevation_' quadBasenameBase], ...
    'SlicedByClinicalNoteColorByClinicalNotes');

rowHasNote = Quad_has_clinical_note(allQuadDataBase);
participantIDs = unique(allQuadDataBase.ID);
idHasNote = false(numel(participantIDs), 1);
for participantIdx = 1:numel(participantIDs)
    participantRows = allQuadDataBase.ID == participantIDs(participantIdx);
    idHasNote(participantIdx) = any(rowHasNote(participantRows));
end

%% Run only the two clinical-note slices
for runIdx = 1:numel(runConfigs)
    runConfig = runConfigs{runIdx};
    selectedIDs = participantIDs(idHasNote == runConfig.hasClinicalNote);
    allQuadData = allQuadDataBase(ismember(allQuadDataBase.ID, selectedIDs), :);
    quadBasename = [quadBasenameBase runConfig.basenameSuffix];
    groupResultsDir = fullfile(resultsRoot, runConfig.resultsSubdir);
    if ~exist(groupResultsDir, 'dir'), mkdir(groupResultsDir); end
    fprintf('Running %s (%d of %d): %d rows from %d participants.\n', ...
        runConfig.resultsSubdir, runIdx, numel(runConfigs), ...
        height(allQuadData), numel(unique(allQuadData.ID)));

    colorConfig = Quad_build_participant_color_config(allQuadData, ...
        groupResultsDir, quadBasename, colorMode, true);
    [~, transformInfo] = apply_quad_elevation_transform(allQuadData(1, :), transformId);
    transformResultsDir = fullfile(groupResultsDir, char(transformInfo.sfx));
    analysisSpecs = quadBuildDisparityAnalysisSpecs(allQuadData, versionLabels);
    modelStore = struct();
    summaryStore = struct();

    for versionIdx = 1:numel(analysisSpecs)
        versionLabel = analysisSpecs(versionIdx).Label;
        versionField = matlab.lang.makeValidName(char(versionLabel));
        tableSubset = analysisSpecs(versionIdx).Table;
        [tableSubset, ~] = apply_quad_elevation_transform(tableSubset, transformId);
        versionResultsDir = fullfile(transformResultsDir, char(versionLabel));
        if ~exist(versionResultsDir, 'dir'), mkdir(versionResultsDir); end
        tableName = sprintf('%s_%s_%s', quadBasename, versionLabel, transformInfo.sfx);
        tableSubset = quadFilterDisparityOutliers(tableSubset, transformId, ...
            removeOutlierParticipants, removeZScoreOutliers, zScoreThreshold, ...
            versionResultsDir, tableName);

        [distanceRI, elevationRI, distanceElevationRI] = ...
            Quad_PerceivedDisparity_by_DistanceElevation(tableSubset, ...
            tableName, versionResultsDir, saveLME, colorConfig.RankCmap, ...
            colorConfig.SortedIdx, transformId, 1, colorConfig.ID, ...
            removeOutlierParticipants, secondYAxisColor, colorConfig);
        [distanceSingleRI, elevationSingleRI, distanceRS, elevationRS] = ...
            Quad_PerceivedDisparity_by_DistanceElevation_single( ...
            tableSubset, tableName, versionResultsDir, saveLME, ...
            colorConfig.RankCmap, colorConfig.SortedIdx, transformId, 1, ...
            colorConfig.ID, removeOutlierParticipants, 'Clinical notes', ...
            secondYAxisColor, false, colorConfig, false);
        summaryStore.(versionField) = ...
            Quad_export_PercievedDisparity_LME_summary_csv(quadBasename, ...
            [], distanceRI, elevationRI, [], [], distanceElevationRI, [], ...
            fullfile(versionResultsDir, [tableName '_lme_summary.csv']));
        modelStore.(versionField) = struct('DistanceRI', distanceRI, ...
            'ElevationRI', elevationRI, ...
            'DistanceElevationRI', distanceElevationRI, ...
            'DistanceSingleRI', distanceSingleRI, ...
            'ElevationSingleRI', elevationSingleRI, ...
            'DistanceRS', distanceRS, 'ElevationRS', elevationRS);
        quadCloseFigures();
    end

    save(fullfile(groupResultsDir, ...
        [quadBasename '_clinical_note_slice_disparity_results.mat']), ...
        'summaryStore', 'modelStore', 'colorConfig', 'transformId', ...
        'colorMode', 'removeOutlierParticipants', 'removeZScoreOutliers');
end

%% Formal no-note versus clinical-note distance/elevation RS-LMM comparisons
formalRoot = fullfile(resultsRoot, 'FormalClinicalNoteGroupComparison', ...
    'absElevation');
formalSpecs = quadBuildDisparityAnalysisSpecs(allQuadDataBase, versionLabels);
for versionIdx = 1:numel(formalSpecs)
    versionLabel = formalSpecs(versionIdx).Label;
    versionData = formalSpecs(versionIdx).Table;
    [versionData, ~] = apply_quad_elevation_transform(versionData, transformId);
    versionData = Quad_prepare_perceived_disparity_table( ...
        versionData, transformId, removeOutlierParticipants);
    versionResultsDir = fullfile(formalRoot, char(versionLabel));
    formalColorConfig = Quad_build_participant_color_config(versionData, ...
        versionResultsDir, sprintf('%s_%s_clinical_note_groups', ...
        quadBasenameBase, versionLabel), 'clinicalnotes', true);
    [participantTbl, statisticsTbl, baseModels, groupModels] = ...
        Quad_compare_clinical_note_groups_RS_LMM(versionData, ...
        'log2mean_disparity', ["log2distance", "log2elevation"], ...
        ["Distance", "Elevation"], versionLabel, quadBasenameBase, ...
        versionResultsDir, formalColorConfig, ...
        'Perceived disparity at mean predictor [deg]', true);
    save(fullfile(versionResultsDir, sprintf( ...
        '%s_%s_clinical_note_group_RS_LMM_results.mat', ...
        quadBasenameBase, versionLabel)), 'participantTbl', ...
        'statisticsTbl', 'baseModels', 'groupModels', 'transformId', ...
        'colorMode');
end
quadFinalizeAnalysis();
