% Paper2_angle_distance_elevation_MergedMatchingClinicalNotes072126
% Run matching analyses separately for participants with and without a
% clinical note, color exclusively by clinical-note category, and formally
% compare the two groups with combined random-slope LMMs.

clear;
close all force;
clc;

scriptDir = fileparts(mfilename('fullpath'));
codeDir = fileparts(scriptDir);
addpath(genpath(codeDir));

%% Configuration
quadFile = fullfile(codeDir, '..', 'QuadExperiments', 'Data', ...
    'merged_matching_0429_x7001.csv');
transformId = 2; % abs(Elevation)
colorMode = "clinicalnotes";
saveLME = true;
runConfigs = { ...
    struct('resultsSubdir', 'NoClinicalNote', ...
        'basenameSuffix', '_noClinicalNote', 'hasClinicalNote', false), ...
    struct('resultsSubdir', 'ClinicalNote', ...
        'basenameSuffix', '_withClinicalNote', 'hasClinicalNote', true) ...
    };
resultsRoot = fullfile(codeDir, '..', 'Paper2Figures', ...
    'MatchingSlicedByClinicalNoteColorByClinicalNotes');

%% Load and define the two participant groups
importOptions = detectImportOptions(quadFile, 'VariableNamingRule', 'modify');
importOptions = setvartype(importOptions, 'ClinicalNotes', 'string');
allQuadDataBase = readtable(quadFile, importOptions);
[~, quadBasenameBase] = fileparts(quadFile);
participantHasNote = Quad_has_clinical_note(allQuadDataBase);
participantIDs = unique(allQuadDataBase.ID);
idHasNote = false(numel(participantIDs), 1);
for participantIdx = 1:numel(participantIDs)
    participantRows = allQuadDataBase.ID == participantIDs(participantIdx);
    idHasNote(participantIdx) = any(participantHasNote(participantRows));
end

for runIdx = 1:numel(runConfigs)
    runConfig = runConfigs{runIdx};
    selectedIDs = participantIDs(idHasNote == runConfig.hasClinicalNote);
    allQuadData = allQuadDataBase(ismember(allQuadDataBase.ID, selectedIDs), :);
    quadBasename = [quadBasenameBase runConfig.basenameSuffix];
    baseResultsDir = fullfile(resultsRoot, runConfig.resultsSubdir);
    if ~exist(baseResultsDir, 'dir'), mkdir(baseResultsDir); end

    fprintf('Running %s (%d of %d): %d rows from %d participants.\n', ...
        runConfig.resultsSubdir, runIdx, numel(runConfigs), ...
        height(allQuadData), numel(unique(allQuadData.ID)));
    allQuadData.Elevation = allQuadData.Observer_Elevation;
    allQuadData.Distance = allQuadData.Observer_Distance;
    quadSubsetData = table(allQuadData.ID, allQuadData.Measurement, ...
        allQuadData.Real_Visual_Angle, allQuadData.Distance / 100, ...
        allQuadData.Elevation, allQuadData.Task, ...
        allQuadData.Reported_Visual_Angle, allQuadData.Ratio_Visual_Angle, ...
        'VariableNames', {'ID', 'Measurement', 'Real_Visual_Angle', ...
        'Distance', 'Elevation', 'Task', 'Reported_Visual_Angle', ...
        'Ratio_Visual_Angle'});

    colorConfig = Quad_build_participant_color_config(allQuadData, ...
        baseResultsDir, quadBasename, colorMode, true);
    [transformSuffix, ~, modelTransform] = get_quad_transform_spec(transformId);
    resultsDir = fullfile(baseResultsDir, transformSuffix);
    if ~exist(resultsDir, 'dir'), mkdir(resultsDir); end
    taskOrder = {'Perceptual', 'Adjusted'};
    taskData = struct( ...
        'Perceptual', quadSubsetData(strcmp(quadSubsetData.Task, 'Perceptual'), :), ...
        'Adjusted', quadSubsetData(strcmp(quadSubsetData.Task, 'Adjusted'), :));
    threeFactorLME = struct('Perceptual', [], 'Adjusted', []);
    singleRSLME = struct('Perceptual', struct(), 'Adjusted', struct());
    fullModelLME = struct('Perceptual', [], 'Adjusted', []);
    stereoInterceptAnalysis = struct('Perceptual', struct(), 'Adjusted', struct());

    for taskIdx = 1:numel(taskOrder)
        task = taskOrder{taskIdx};
        taskTable = taskData.(task);
        tableName = sprintf('%s_%s_%s', quadBasename, task, transformSuffix);
        [~, ~, ~, angleRS, distanceRS, elevationRS] = ...
            Quad_PM_by_task_single(taskTable, tableName, resultsDir, ...
            saveLME, colorConfig.RankCmap, colorConfig.SortedIdx, modelTransform);
        quadCloseFigures();
        [angleLME, distanceLME, elevationLME, angleDistanceLME, ...
            angleElevationLME, distanceElevationLME, threeFactorModel] = ...
            Quad_PM_by_task(taskTable, tableName, resultsDir, saveLME, ...
            colorConfig.RankCmap, colorConfig.SortedIdx, modelTransform);
        quadCloseFigures();
        fullModel = fit_PM_full_VA_D_E_model(taskTable, ...
            [tableName '_fullmodel_fit'], resultsDir, saveLME, ...
            colorConfig.RankCmap, colorConfig.SortedIdx, modelTransform);
        Quad_export_LME_summary_csv(quadBasename, task, angleLME, ...
            distanceLME, elevationLME, angleDistanceLME, ...
            angleElevationLME, distanceElevationLME, threeFactorModel, ...
            fullfile(resultsDir, [tableName '_lme_summary.csv']));
        threeFactorLME.(task) = threeFactorModel;
        singleRSLME.(task) = struct('Angle', angleRS, ...
            'Distance', distanceRS, 'Elevation', elevationRS);
        fullModelLME.(task) = fullModel;
        taskRows = strcmpi(string(allQuadData.Task), task);
        [interceptTbl, interceptStereoModel] = ...
            Quad_PM_intercepts_by_stereoscore(allQuadData(taskRows, :), ...
            threeFactorModel, tableName, resultsDir, colorConfig);
        stereoInterceptAnalysis.(task) = struct( ...
            'ParticipantIntercepts', interceptTbl, ...
            'StereoModel', interceptStereoModel);
    end

    save(fullfile(resultsRoot, [quadBasename '.mat']), 'allQuadData', ...
        'colorConfig', 'threeFactorLME', 'singleRSLME', 'fullModelLME', ...
        'stereoInterceptAnalysis', ...
        'transformId', 'colorMode');
    quadCloseFigures();
end

%% Formal no-note versus clinical-note RS-LMM comparisons
formalRoot = fullfile(resultsRoot, 'FormalClinicalNoteGroupComparison', ...
    'absElevation');
formalData = allQuadDataBase;
formalData.Distance = double(formalData.Observer_Distance) ./ 100;
formalData.Elevation = abs(double(formalData.Observer_Elevation));
formalData.log2ratio_visual_angle = log2(double(formalData.Ratio_Visual_Angle));
formalData.log2real_visual_angle = log2(double(formalData.Real_Visual_Angle));
formalData.log2distance = log2(formalData.Distance);
formalData.log2elevation = log2(1 + formalData.Elevation);
formalData = formalData(isfinite(formalData.log2ratio_visual_angle) & ...
    isfinite(formalData.log2real_visual_angle) & ...
    isfinite(formalData.log2distance) & isfinite(formalData.log2elevation), :);
formalColorConfig = Quad_build_participant_color_config(formalData, ...
    formalRoot, [quadBasenameBase '_clinical_note_groups'], ...
    'clinicalnotes', true);
for taskIdx = 1:numel(taskOrder)
    task = taskOrder{taskIdx};
    taskTbl = formalData(strcmpi(string(formalData.Task), task), :);
    taskResultsDir = fullfile(formalRoot, task);
    [participantTbl, statisticsTbl, baseModels, groupModels] = ...
        Quad_compare_clinical_note_groups_RS_LMM(taskTbl, ...
        'log2ratio_visual_angle', ...
        ["log2real_visual_angle", "log2distance", "log2elevation"], ...
        ["Angle", "Distance", "Elevation"], task, quadBasenameBase, ...
        taskResultsDir, formalColorConfig, ...
        'Power-law PM intercept at mean predictor', true);
    save(fullfile(taskResultsDir, sprintf( ...
        '%s_%s_clinical_note_group_RS_LMM_results.mat', ...
        quadBasenameBase, task)), 'participantTbl', 'statisticsTbl', ...
        'baseModels', 'groupModels', 'transformId', 'colorMode');
end
quadFinalizeAnalysis();
