function [participantTbl, statisticsTbl, baseModels, groupModels] = ...
    Quad_compare_clinical_note_groups_RS_LMM(tbl, responseName, ...
    predictorNames, factorNames, analysisLabel, quadBasename, resultsDir, ...
    colorConfig, interceptAxisLabel, saveFigure)
%QUAD_COMPARE_CLINICAL_NOTE_GROUPS_RS_LMM Formal no-note versus note comparison.
%
% For each predictor, the base RS LMM is compared with a model containing
% ClinicalNoteGroup and its interaction with the mean-centered predictor.
% NoClinicalNote is the reference group.

if nargin < 9 || isempty(interceptAxisLabel)
    interceptAxisLabel = 'Outcome at mean predictor';
end
if nargin < 10 || isempty(saveFigure)
    saveFigure = true;
end
predictorNames = string(predictorNames(:));
factorNames = string(factorNames(:));
if numel(predictorNames) ~= numel(factorNames)
    error('QuadClinicalGroupRSLMM:FactorCountMismatch', ...
        'predictorNames and factorNames must have the same length.');
end
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

hasNote = Quad_has_clinical_note(tbl);
groupOrder = ["NoClinicalNote", "ClinicalNote"];
groupText = repmat(groupOrder(1), height(tbl), 1);
groupText(hasNote) = groupOrder(2);
tbl.ClinicalNoteGroup = categorical(groupText, groupOrder, groupOrder);
if ~iscategorical(tbl.ID)
    tbl.ID = categorical(tbl.ID);
end

predictorCenters = nan(numel(predictorNames), 1);
for factorIdx = 1:numel(predictorNames)
    predictorCenters(factorIdx) = mean(tbl.(predictorNames(factorIdx)), 'omitnan');
    tbl.(predictorNames(factorIdx)) = tbl.(predictorNames(factorIdx)) - ...
        predictorCenters(factorIdx);
end

baseModels = struct();
groupModels = struct();
participantParts = cell(numel(factorNames), 1);
statisticsParts = cell(numel(factorNames), 1);
comparisonStore = cell(numel(factorNames), 1);

for factorIdx = 1:numel(factorNames)
    factorName = factorNames(factorIdx);
    predictor = predictorNames(factorIdx);
    baseFormula = sprintf('%s ~ %s + (1 + %s|ID)', ...
        responseName, predictor, predictor);
    groupFormula = sprintf(['%s ~ %s*ClinicalNoteGroup + ' ...
        '(1 + %s|ID)'], responseName, predictor, predictor);
    baseModel = fitlme(tbl, baseFormula, 'FitMethod', 'ML');
    groupModel = fitlme(tbl, groupFormula, 'FitMethod', 'ML');
    modelComparison = compare(baseModel, groupModel);
    baseModels.(factorName) = baseModel;
    groupModels.(factorName) = groupModel;
    comparisonStore{factorIdx} = modelComparison;

    coefficientNames = string(groupModel.Coefficients.Name);
    groupCoefficientName = "ClinicalNoteGroup_ClinicalNote";
    interceptIdx = find(coefficientNames == "(Intercept)", 1, 'first');
    predictorIdx = find(coefficientNames == predictor, 1, 'first');
    groupIdx = find(coefficientNames == groupCoefficientName, 1, 'first');
    interactionIdx = find(contains(coefficientNames, predictor) & ...
        contains(coefficientNames, groupCoefficientName), 1, 'first');
    if isempty(groupIdx) || isempty(interactionIdx)
        error('QuadClinicalGroupRSLMM:MissingGroupCoefficient', ...
            'Could not identify clinical-note group coefficients for %s.', factorName);
    end

    participantIDs = string(categories(removecats(tbl.ID)));
    subjectIntercept = Quad_extract_subject_model_coefficient( ...
        groupModel, '(Intercept)', participantIDs);
    subjectSlope = Quad_extract_subject_model_coefficient( ...
        groupModel, predictor, participantIDs);
    participantGroup = strings(numel(participantIDs), 1);
    participantCategory = strings(numel(participantIDs), 1);
    for participantIdx = 1:numel(participantIDs)
        participantRows = string(tbl.ID) == participantIDs(participantIdx);
        participantGroup(participantIdx) = string(tbl.ClinicalNoteGroup( ...
            find(participantRows, 1, 'first')));
        colorIdx = find(string(colorConfig.ID) == participantIDs(participantIdx), 1);
        participantCategory(participantIdx) = colorConfig.Category(colorIdx);
    end
    noteParticipants = participantGroup == groupOrder(2);
    subjectIntercept(noteParticipants) = subjectIntercept(noteParticipants) + ...
        groupModel.Coefficients.Estimate(groupIdx);
    subjectSlope(noteParticipants) = subjectSlope(noteParticipants) + ...
        groupModel.Coefficients.Estimate(interactionIdx);

    participantParts{factorIdx} = table( ...
        repmat(string(analysisLabel), numel(participantIDs), 1), ...
        repmat(factorName, numel(participantIDs), 1), participantIDs, ...
        categorical(participantGroup, groupOrder, groupOrder), ...
        participantCategory, subjectIntercept, 2 .^ subjectIntercept, ...
        subjectSlope, 'VariableNames', {'Analysis', 'Factor', 'ID', ...
        'ClinicalNoteGroup', 'ClinicalCategory', ...
        'SubjectLog2InterceptAtMean', 'SubjectInterceptAtMean', 'SubjectSlope'});

    statisticsParts{factorIdx} = table(string(analysisLabel), factorName, ...
        sum(participantGroup == groupOrder(1)), ...
        sum(participantGroup == groupOrder(2)), predictorCenters(factorIdx), ...
        groupModel.Coefficients.Estimate(interceptIdx), ...
        groupModel.Coefficients.Estimate(groupIdx), ...
        groupModel.Coefficients.pValue(groupIdx), ...
        groupModel.Coefficients.Estimate(predictorIdx), ...
        groupModel.Coefficients.Estimate(interactionIdx), ...
        groupModel.Coefficients.pValue(interactionIdx), ...
        modelComparison.pValue(2), baseModel.ModelCriterion.AIC, ...
        groupModel.ModelCriterion.AIC, ...
        'VariableNames', {'Analysis', 'Factor', 'NNoClinicalNote', ...
        'NClinicalNote', 'PredictorCenter', 'NoNoteInterceptAtMean', ...
        'ClinicalNoteMinusNoNoteIntercept', 'InterceptGroupPValue', ...
        'NoNoteSlope', 'ClinicalNoteMinusNoNoteSlope', ...
        'SlopeInteractionPValue', 'JointGroupAndInteractionLRPValue', ...
        'BaseAIC', 'GroupAIC'});
end

participantTbl = vertcat(participantParts{:});
statisticsTbl = vertcat(statisticsParts{:});
fileStem = sprintf('%s_%s_clinical_note_group_RS_LMM', ...
    quadBasename, analysisLabel);
writetable(participantTbl, fullfile(resultsDir, [fileStem '_participants.csv']));
writetable(statisticsTbl, fullfile(resultsDir, [fileStem '_statistics.csv']));

reportFile = fullfile(resultsDir, [fileStem '_models.txt']);
fileID = fopen(reportFile, 'w');
if fileID == -1
    error('QuadClinicalGroupRSLMM:ReportOpenFailed', ...
        'Could not open report file %s.', reportFile);
end
cleanupObject = onCleanup(@() fclose(fileID));
fprintf(fileID, 'Clinical-note-presence RS-LMM analysis: %s\n', analysisLabel);
fprintf(fileID, 'NoClinicalNote is the reference group; predictors are mean-centered.\n\n');
for factorIdx = 1:numel(factorNames)
    factorName = factorNames(factorIdx);
    fprintf(fileID, '===== %s =====\n', factorName);
    Quad_write_compact_lme_report(fileID, 'Base model', ...
        baseModels.(factorName));
    Quad_write_compact_lme_report(fileID, 'Clinical-note group model', ...
        groupModels.(factorName));
    Quad_write_compact_model_comparison(fileID, ...
        ['Joint likelihood-ratio test: clinical-note group intercept ' ...
        'difference + group-by-predictor slope difference'], ...
        comparisonStore{factorIdx});
end

if ~saveFigure
    return;
end

nFactors = numel(factorNames);
figH = figure('Color', [1 1 1], 'Units', 'normalized', ...
    'Position', [0.02 0.05 0.96 0.88], 'Name', fileStem, 'Visible', 'off');
tiled = tiledlayout(figH, 2, nFactors, 'Padding', 'compact', ...
    'TileSpacing', 'compact');
tiled.Position = [0.07 0.10 0.76 0.80];
axesList = gobjects(2 * nFactors, 1);
for factorIdx = 1:nFactors
    factorTbl = participantParts{factorIdx};
    x = Quad_group_plot_x_positions(factorTbl.ClinicalNoteGroup, groupOrder);

    axIntercept = nexttile(tiled, factorIdx);
    axesList(factorIdx) = axIntercept;
    hold(axIntercept, 'on');
    Quad_plot_group_participant_points(axIntercept, x, ...
        factorTbl.SubjectInterceptAtMean, factorTbl.ID, colorConfig);
    Quad_plot_group_means(axIntercept, factorTbl.ClinicalNoteGroup, ...
        factorTbl.SubjectInterceptAtMean, groupOrder);
    set(axIntercept, 'XLim', [0.5 2.5], 'XTick', 1:2, ...
        'XTickLabel', {'No note', 'Clinical note'}, ...
        'FontName', 'Avenir', 'FontSize', 13);
    ylabel(axIntercept, interceptAxisLabel, 'FontSize', 14);
    title(axIntercept, sprintf(['%s intercept\nClinical-note group ' ...
        'difference p=%s'], factorNames(factorIdx), ...
        Quad_format_pvalue(statisticsTbl.InterceptGroupPValue(factorIdx))), ...
        'FontSize', 13, 'FontWeight', 'normal');
    box(axIntercept, 'off');

    axSlope = nexttile(tiled, factorIdx + nFactors);
    axesList(factorIdx + nFactors) = axSlope;
    hold(axSlope, 'on');
    Quad_plot_group_participant_points(axSlope, x, factorTbl.SubjectSlope, ...
        factorTbl.ID, colorConfig);
    Quad_plot_group_means(axSlope, factorTbl.ClinicalNoteGroup, ...
        factorTbl.SubjectSlope, groupOrder);
    yline(axSlope, 0, 'k-', 'LineWidth', 1);
    set(axSlope, 'XLim', [0.5 2.5], 'XTick', 1:2, ...
        'XTickLabel', {'No note', 'Clinical note'}, ...
        'FontName', 'Avenir', 'FontSize', 13);
    ylabel(axSlope, 'Subject slope', 'FontSize', 14);
    title(axSlope, sprintf(['%s slope\nClinical-note group slope ' ...
        'difference p=%s\nJoint intercept+slope LRT p=%s'], ...
        factorNames(factorIdx), ...
        Quad_format_pvalue(statisticsTbl.SlopeInteractionPValue(factorIdx)), ...
        Quad_format_pvalue(statisticsTbl.JointGroupAndInteractionLRPValue(factorIdx))), ...
        'FontSize', 13, 'FontWeight', 'normal');
    box(axSlope, 'off');
end
title(tiled, sprintf('%s: no clinical note versus clinical note RS LMM', ...
    analysisLabel), 'FontName', 'Avenir', 'FontSize', 18, ...
    'FontWeight', 'normal');
Quad_finish_group_color_key(axesList, colorConfig);
exportgraphics(figH, fullfile(resultsDir, [fileStem '.png']), 'Resolution', 600);
close(figH);
end
