function [interceptTbl, comparisonTbl] = ...
    Quad_PM_compare_intercepts_across_stereo_groups( ...
    tblTypical, lmeTypical, tblDeficient, lmeDeficient, taskName, ...
    quadBasename, resultsDir, saveFigure, colorConfig)
%QUAD_PM_COMPARE_INTERCEPTS_ACROSS_STEREO_GROUPS Compare subject intercepts.
% Typical and StereoBlind participants are independent groups, so the
% figure uses side-by-side participant distributions rather than paired axes.

if nargin < 8 || isempty(saveFigure)
    saveFigure = true;
end
if nargin < 9 || isempty(colorConfig)
    error('QuadGroupIntercepts:MissingColorConfig', ...
        'A participant color configuration is required.');
end
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

typicalIDs = unique(string(tblTypical.ID), 'stable');
deficientIDs = unique(string(tblDeficient.ID), 'stable');
typicalLogIntercept = Quad_extract_subject_model_coefficient( ...
    lmeTypical, '(Intercept)', typicalIDs);
deficientLogIntercept = Quad_extract_subject_model_coefficient( ...
    lmeDeficient, '(Intercept)', deficientIDs);

groupOrder = ["StereoTypical", "StereoBlind"];
groupText = [repmat(groupOrder(1), numel(typicalIDs), 1); ...
    repmat(groupOrder(2), numel(deficientIDs), 1)];
interceptTbl = table( ...
    [typicalIDs; deficientIDs], ...
    categorical(groupText, groupOrder, groupOrder), ...
    [typicalLogIntercept; deficientLogIntercept], ...
    2 .^ [typicalLogIntercept; deficientLogIntercept], ...
    'VariableNames', {'ID', 'StereoGroup', 'Log2Intercept', 'PowerLawIntercept'});
interceptTbl = sortrows(interceptTbl, {'StereoGroup', 'ID'});

validRows = isfinite(interceptTbl.Log2Intercept);
comparisonModel = fitlm(interceptTbl(validRows, :), ...
    'Log2Intercept ~ StereoGroup');
groupPValue = comparisonModel.Coefficients.pValue(2);

comparisonTbl = table(string(taskName), ...
    sum(interceptTbl.StereoGroup == groupOrder(1)), ...
    sum(interceptTbl.StereoGroup == groupOrder(2)), ...
    mean(interceptTbl.Log2Intercept(interceptTbl.StereoGroup == groupOrder(1)), 'omitnan'), ...
    mean(interceptTbl.Log2Intercept(interceptTbl.StereoGroup == groupOrder(2)), 'omitnan'), ...
    comparisonModel.Coefficients.Estimate(2), groupPValue, ...
    'VariableNames', {'Task', 'NTypical', 'NDeficient', ...
    'MeanLog2InterceptTypical', 'MeanLog2InterceptDeficient', ...
    'DeficientMinusTypical', 'ExploratoryPValue'});

fileStem = sprintf('%s_%s_PM_intercepts_across_stereo_groups', ...
    quadBasename, taskName);
writetable(interceptTbl, fullfile(resultsDir, [fileStem '_participants.csv']));
writetable(comparisonTbl, fullfile(resultsDir, [fileStem '_comparison.csv']));

if ~saveFigure
    return;
end

figH = figure('Color', [1 1 1], 'Units', 'normalized', ...
    'Position', [0.18 0.18 0.62 0.65], 'Name', fileStem, 'Visible', 'off');
ax = axes(figH, 'Position', [0.14 0.15 0.68 0.72]);
hold(ax, 'on');
x = Quad_group_plot_x_positions(interceptTbl.StereoGroup, groupOrder);
Quad_plot_group_participant_points(ax, x, interceptTbl.PowerLawIntercept, ...
    interceptTbl.ID, colorConfig);

for groupIdx = 1:numel(groupOrder)
    groupValues = interceptTbl.PowerLawIntercept( ...
        string(interceptTbl.StereoGroup) == groupOrder(groupIdx));
    groupMean = mean(groupValues, 'omitnan');
    plot(ax, groupIdx + [-0.22 0.22], [groupMean groupMean], 'k-', 'LineWidth', 4);
end

set(ax, 'XLim', [0.5 2.5], 'XTick', 1:2, ...
    'XTickLabel', {'StereoTypical', 'StereoBlind'}, ...
    'FontName', 'Avenir', 'FontSize', 17);
ylabel(ax, 'Subject power-law intercept [2^{log_2 PM}]', 'FontSize', 20);
title(ax, sprintf('%s: intercepts across stereo groups\ntwo-stage p=%s, n=%d vs %d', ...
    taskName, Quad_format_pvalue(groupPValue), comparisonTbl.NTypical, ...
    comparisonTbl.NDeficient), 'FontSize', 16, 'FontWeight', 'normal');
box(ax, 'off');
grid(ax, 'off');
Quad_finish_group_color_key(ax, colorConfig);
exportgraphics(figH, fullfile(resultsDir, [fileStem '.png']), 'Resolution', 600);
close(figH);
end
