function Quad_write_compact_lme_report(fileID, modelLabel, lmeModel)
%QUAD_WRITE_COMPACT_LME_REPORT Write one fixed-effect coefficient per line.

fprintf(fileID, '%s\n', modelLabel);
fprintf(fileID, 'Formula: %s\n', char(lmeModel.Formula));
fprintf(fileID, ['Observations: %d   AIC: %.6g   BIC: %.6g   ' ...
    'LogLikelihood: %.6g   Deviance: %.6g\n'], ...
    lmeModel.NumObservations, lmeModel.ModelCriterion.AIC, ...
    lmeModel.ModelCriterion.BIC, lmeModel.LogLikelihood, ...
    -2 * lmeModel.LogLikelihood);
fprintf(fileID, 'Fixed effects (95%% confidence intervals):\n');
fprintf(fileID, '%-46s %12s %12s %12s %8s %12s %12s %12s\n', ...
    'Parameter', 'Estimate', 'SE', 'tStat', 'DF', 'pValue', 'Lower', 'Upper');

coefficientTbl = lmeModel.Coefficients;
for coefficientIdx = 1:height(coefficientTbl)
    parameterName = string(coefficientTbl.Name(coefficientIdx));
    parameterName = erase(parameterName, 'centered_');
    parameterName = replace(parameterName, ...
        'StereoGroup_StereoDeficient', 'StereoGroup_Deficient');
    fprintf(fileID, '%-46s %12.6g %12.6g %12.6g %8.0f %12.6g %12.6g %12.6g\n', ...
        parameterName, coefficientTbl.Estimate(coefficientIdx), ...
        coefficientTbl.SE(coefficientIdx), coefficientTbl.tStat(coefficientIdx), ...
        coefficientTbl.DF(coefficientIdx), coefficientTbl.pValue(coefficientIdx), ...
        coefficientTbl.Lower(coefficientIdx), coefficientTbl.Upper(coefficientIdx));
end
fprintf(fileID, '\n');
end
