function [lmeRI, lmeRS, lmeElevationRI, lmeElevationRS] = ...
    Quad_DistancefromMeanPerceivedParallax( ...
    tbl, tblName, ResultsDir, saveLME, cmap, sortedIdx, fullUniqueID, ...
    colorbarLabel, colorConfig)
% QUAD_DISTANCEFROMMEANPERCEIVEDPARALLAX
% Estimate fixation distance after averaging the two disparity and caliper
% measurements within each source-table row.

[lmeRI, lmeRS, lmeElevationRI, lmeElevationRS] = ...
    Quad_DistancefromPerceivedParallax( ...
    tbl, tblName, ResultsDir, saveLME, cmap, sortedIdx, fullUniqueID, ...
    colorbarLabel, colorConfig, "mean");
end
