function [testSummary, participantTbl, groupSummaryTbl, groupModel] = ...
    compute_mean_pm_stereo_group_test(tbl, reportFile, sourceFile)
%COMPUTE_MEAN_PM_STEREO_GROUP_TEST Compare participant mean PM across groups.
%
% Each participant contributes one mean Ratio_Visual_Angle. A linear model
% tests whether those independent participant means differ by StereoGroup.

if nargin < 2
    reportFile = '';
end
if nargin < 3 || isempty(sourceFile)
    sourceFile = 'Input MATLAB table';
end

requiredVars = {'ID', 'StereoGroup', 'Ratio_Visual_Angle'};
missingVars = setdiff(requiredVars, tbl.Properties.VariableNames);
if ~isempty(missingVars)
    error('MeanPMStereoGroupTest:MissingVariables', ...
        'tbl is missing required variable(s): %s', strjoin(missingVars, ', '));
end

rowID = string(tbl.ID);
rowGroup = string(tbl.StereoGroup);
rowPM = double(tbl.Ratio_Visual_Angle);
validRows = ~ismissing(rowID) & ~ismissing(rowGroup) & isfinite(rowPM);
rowID = rowID(validRows);
rowGroup = rowGroup(validRows);
rowPM = rowPM(validRows);

participantIDs = unique(rowID, 'stable');
participantGroups = strings(numel(participantIDs), 1);
meanPM = nan(numel(participantIDs), 1);
for participantIdx = 1:numel(participantIDs)
    participantRows = rowID == participantIDs(participantIdx);
    thisGroups = unique(rowGroup(participantRows));
    if numel(thisGroups) ~= 1
        error('MeanPMStereoGroupTest:MultipleGroupsPerParticipant', ...
            'Participant %s appears in multiple stereo groups.', ...
            participantIDs(participantIdx));
    end
    participantGroups(participantIdx) = thisGroups;
    meanPM(participantIdx) = mean(rowPM(participantRows), 'omitnan');
end

groupOrder = local_group_order(unique(participantGroups, 'stable'));
participantTbl = table(participantIDs, ...
    categorical(participantGroups, groupOrder, groupOrder), meanPM, ...
    'VariableNames', {'ID', 'StereoGroup', 'MeanPM'});

if numel(groupOrder) < 2
    error('MeanPMStereoGroupTest:TooFewGroups', ...
        'At least two stereo groups are required.');
end

groupModel = fitlm(participantTbl, 'MeanPM ~ StereoGroup');
[pValue, fStat, numeratorDF] = coefTest(groupModel);
denominatorDF = groupModel.DFE;

nGroups = numel(groupOrder);
groupN = zeros(nGroups, 1);
groupMean = nan(nGroups, 1);
groupSD = nan(nGroups, 1);
for groupIdx = 1:nGroups
    groupRows = string(participantTbl.StereoGroup) == groupOrder(groupIdx);
    groupN(groupIdx) = sum(groupRows);
    groupMean(groupIdx) = mean(participantTbl.MeanPM(groupRows), 'omitnan');
    groupSD(groupIdx) = std(participantTbl.MeanPM(groupRows), 'omitnan');
end
groupSummaryTbl = table(categorical(groupOrder(:), groupOrder, groupOrder), ...
    groupN, groupMean, groupSD, ...
    'VariableNames', {'StereoGroup', 'NParticipants', 'MeanPM', 'SDPM'});

testSummary = struct();
testSummary.NParticipants = height(participantTbl);
testSummary.NGroups = nGroups;
testSummary.FStat = fStat;
testSummary.NumeratorDF = numeratorDF;
testSummary.DenominatorDF = denominatorDF;
testSummary.PValue = pValue;
testSummary.ReportLine = sprintf( ...
    'Participant mean PM by StereoGroup: F(%d, %d) = %.3f, p = %s', ...
    numeratorDF, denominatorDF, fStat, Quad_format_pvalue(pValue));

if strlength(string(reportFile)) > 0
    local_write_report(reportFile, sourceFile, testSummary, ...
        participantTbl, groupSummaryTbl, groupModel);
end
end

function groupOrder = local_group_order(groupsPresent)
preferredOrder = ["StereoTypical", "StereoDeficient", "StereoBlind"];
groupOrder = preferredOrder(ismember(preferredOrder, groupsPresent));
remainingGroups = groupsPresent(~ismember(groupsPresent, groupOrder));
groupOrder = [groupOrder, remainingGroups(:)'];
end

function local_write_report(reportFile, sourceFile, testSummary, ...
    participantTbl, groupSummaryTbl, groupModel)
[reportDir, reportStem] = fileparts(reportFile);
if ~isempty(reportDir) && ~exist(reportDir, 'dir')
    mkdir(reportDir);
end

fid = fopen(reportFile, 'w');
if fid == -1
    error('MeanPMStereoGroupTest:CannotOpenReport', ...
        'Could not open report file: %s', reportFile);
end
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

reportTitle = 'Participant Mean Perceptual Magnification by Stereo Group';
fprintf(fid, '%s\n%s\n\n', reportTitle, repmat('=', 1, strlength(reportTitle)));
fprintf(fid, 'Generated: %s\n', char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')));
fprintf(fid, 'Generated by: %s\n', mfilename);
fprintf(fid, 'Source CSV: %s\n', char(string(sourceFile)));
fprintf(fid, 'Unit of analysis: one mean Ratio_Visual_Angle per participant\n');
fprintf(fid, 'Model: MeanPM ~ StereoGroup\n\n');

fprintf(fid, 'Group descriptives:\n');
fprintf(fid, '%-22s %14s %14s %14s\n', ...
    'StereoGroup', 'N participants', 'Mean PM', 'SD PM');
for rowIdx = 1:height(groupSummaryTbl)
    fprintf(fid, '%-22s %14d %14.4f %14.4f\n', ...
        char(string(groupSummaryTbl.StereoGroup(rowIdx))), ...
        groupSummaryTbl.NParticipants(rowIdx), ...
        groupSummaryTbl.MeanPM(rowIdx), groupSummaryTbl.SDPM(rowIdx));
end

fprintf(fid, '\nOmnibus stereo-group test:\n%s\n\n', testSummary.ReportLine);
fprintf(fid, 'Model coefficients:\n');
coefficientText = clean_matlab_display_text(evalc('disp(groupModel.Coefficients)'));
fprintf(fid, '%s\n', coefficientText);

participantFile = fullfile(reportDir, [reportStem '_participants.csv']);
writetable(participantTbl, participantFile);
fprintf(fid, 'Participant-level CSV: %s\n', participantFile);
end
