function [reportFile, fixedEffectsTbl] = write_lme_stats_report(lme, reportFile, opts)
% write_lme_stats_report
%
% Write a reusable text report for a MATLAB LinearMixedModel. The report
% records provenance and then preserves MATLAB's model display with light
% cleanup for easier reading.
%
% Inputs
%   lme        : fitted LinearMixedModel
%   reportFile : output .txt file path
%   opts       : optional struct with fields:
%                ReportTitle, GeneratedBy, SourceFile, ModelLabel, Task,
%                SummaryLines, FixedEffectsCsvFile, Models, ModelLabels,
%                Comparisons, ComparisonLabels, RemoveGroupError
%
% Outputs
%   reportFile      : full path to written text report
%   fixedEffectsTbl : tidy table of fixed-effect estimates

if nargin < 1 || isempty(lme)
    error('lme is required.');
end
if nargin < 2 || isempty(reportFile)
    error('reportFile is required.');
end
if nargin < 3 || isempty(opts)
    opts = struct();
end
if ~isstruct(opts)
    error('opts must be a struct.');
end

reportFile = char(string(reportFile));
[reportDir,~,~] = fileparts(reportFile);
if ~isempty(reportDir) && ~exist(reportDir, 'dir')
    mkdir(reportDir);
end

models = local_get_models(lme, opts);
modelLabels = local_get_labels(opts, 'ModelLabels', '', numel(models));
comparisons = local_get_cell_option(opts, 'Comparisons');
comparisonLabels = local_get_labels(opts, 'ComparisonLabels', '', numel(comparisons));
removeGroupError = local_get_option(opts, 'RemoveGroupError', true);

fixedEffectsTbl = local_fixed_effects_table(models{1});
fixedEffectsCsvFile = local_get_option(opts, 'FixedEffectsCsvFile', '');
if ~isempty(fixedEffectsCsvFile)
    fixedEffectsCsvFile = char(string(fixedEffectsCsvFile));
    [csvDir,~,~] = fileparts(fixedEffectsCsvFile);
    if ~isempty(csvDir) && ~exist(csvDir, 'dir')
        mkdir(csvDir);
    end
    writetable(fixedEffectsTbl, fixedEffectsCsvFile);
end

[fid, msg] = fopen(reportFile, 'w');
if fid == -1
    error('Could not open report file %s: %s', reportFile, msg);
end
cleanupObj = onCleanup(@() fclose(fid));

reportTitle = local_get_option(opts, 'ReportTitle', 'Linear Mixed-Effects Model Report');
reportTitle = char(string(reportTitle));

fprintf(fid, '%s\n', reportTitle);
fprintf(fid, '%s\n\n', repmat('=', 1, numel(reportTitle)));
fprintf(fid, 'Generated: %s\n', char(string(datetime("now", "Format", "yyyy-MM-dd HH:mm:ss"))));
fprintf(fid, 'Generated by: %s\n', char(string(local_get_option(opts, 'GeneratedBy', '<not specified>'))));
fprintf(fid, 'Source CSV: %s\n', char(string(local_get_option(opts, 'SourceFile', '<not specified>'))));

modelLabel = local_get_option(opts, 'ModelLabel', '');
if ~isempty(modelLabel)
    fprintf(fid, 'Model label: %s\n', char(string(modelLabel)));
end
taskLabel = local_get_option(opts, 'Task', '');
if ~isempty(taskLabel)
    fprintf(fid, 'Task: %s\n', char(string(taskLabel)));
end
fprintf(fid, '\n');

summaryLines = local_get_option(opts, 'SummaryLines', {});
local_write_lines(fid, summaryLines);

for iModel = 1:numel(models)
    local_write_named_block(fid, modelLabels{iModel}, local_capture_display(models{iModel}, removeGroupError));
end

for iComparison = 1:numel(comparisons)
    local_write_named_block(fid, comparisonLabels{iComparison}, local_capture_display(comparisons{iComparison}, false));
end
end

function models = local_get_models(lme, opts)
if isfield(opts, 'Models') && ~isempty(opts.Models)
    models = local_as_cell(opts.Models);
else
    models = {lme};
end
end

function values = local_as_cell(values)
if iscell(values)
    return;
end
values = {values};
end

function labels = local_get_labels(opts, listFieldName, singleFieldName, nLabels)
labels = cell(1, nLabels);
if isfield(opts, listFieldName) && ~isempty(opts.(listFieldName))
    rawLabels = cellstr(string(opts.(listFieldName)));
else
    singleLabel = "";
    if ~isempty(singleFieldName) && isfield(opts, singleFieldName) && ~isempty(opts.(singleFieldName))
        singleLabel = string(opts.(singleFieldName));
    end
    rawLabels = cellstr(singleLabel);
end

for iLabel = 1:nLabels
    if iLabel <= numel(rawLabels) && strlength(string(rawLabels{iLabel})) > 0
        labels{iLabel} = char(string(rawLabels{iLabel}));
    elseif nLabels == 1
        labels{iLabel} = '';
    else
        labels{iLabel} = sprintf('Model %d', iLabel);
    end
end
end

function values = local_get_cell_option(opts, fieldName)
if isfield(opts, fieldName) && ~isempty(opts.(fieldName))
    values = local_as_cell(opts.(fieldName));
else
    values = {};
end
end

function local_write_named_block(fid, labelText, blockText)
if ~isempty(labelText)
    fprintf(fid, '%s\n', labelText);
    fprintf(fid, '%s\n', repmat('-', 1, numel(labelText)));
end
fprintf(fid, '%s\n\n', blockText);
end

function fixedEffectsTbl = local_fixed_effects_table(lme)
ct = lme.Coefficients;
nRows = height(ct);
varNames = local_var_names(ct);

if ismember('Name', varNames)
    termNames = string(ct.Name);
else
    termNames = string(lme.CoefficientNames(:));
end
termNames = replace(termNames, "(Intercept)", "Intercept");

estimate = local_coef_column(ct, 'Estimate');
se = local_coef_column(ct, 'SE');
df = local_coef_column(ct, 'DF');
tStat = local_coef_column(ct, 'tStat');
pValue = local_coef_column(ct, 'pValue');
lower95 = local_coef_column(ct, 'Lower');
upper95 = local_coef_column(ct, 'Upper');

pText = strings(nRows, 1);
for iRow = 1:nRows
    pText(iRow) = string(local_format_p_value(pValue(iRow)));
end

fixedEffectsTbl = table(termNames(:), estimate, se, df, tStat, pValue, pText, lower95, upper95, ...
    'VariableNames', {'Term','Estimate','SE','DF','tStat','pValue','pText','Lower95','Upper95'});
end

function values = local_coef_column(coefTbl, varName)
if ismember(varName, local_var_names(coefTbl))
    values = double(coefTbl.(varName));
else
    values = nan(height(coefTbl), 1);
end
end

function varNames = local_var_names(dataArray)
try
    varNames = cellstr(dataArray.Properties.VariableNames);
    return;
catch
end

try
    varNames = cellstr(dataArray.Properties.VarNames);
    return;
catch
end

try
    varNames = fieldnames(dataArray);
    return;
catch
end

varNames = {};
end

function local_write_lines(fid, lines)
if isempty(lines)
    return;
end

lines = cellstr(string(lines));
for iLine = 1:numel(lines)
    fprintf(fid, '%s\n', lines{iLine});
end
fprintf(fid, '\n');
end

function value = local_get_option(opts, fieldName, defaultValue)
if isfield(opts, fieldName) && ~isempty(opts.(fieldName))
    value = opts.(fieldName);
else
    value = defaultValue;
end
end

function pText = local_format_p_value(pValue)
if isnan(pValue)
    pText = 'p = NA';
elseif pValue < 0.001
    pText = 'p < 0.001';
else
    pText = sprintf('p = %.3f', pValue);
end
end

function displayText = local_capture_display(value, removeGroupError)
if nargin < 2
    removeGroupError = true;
end
displayText = evalc('disp(value)');
displayText = clean_matlab_display_text(displayText, removeGroupError);
end
