function write_bin_error_report(reportFilename, modelErrorSummaryTbl, reportTbl, opts)
% write_bin_error_report Write a binned model-error text report.
%
% write_bin_error_report(reportFilename, modelErrorSummaryTbl, reportTbl, opts)
%
% Inputs
%   reportFilename       : output text file.
%   modelErrorSummaryTbl : model-level error summary table.
%   reportTbl            : bin-level error table.
%   opts                 : optional struct with fields:
%                          Param, minNID, didRebin, rebinTolPct, figName,
%                          reportModelLabel, generatedBy.

if nargin < 4 || isempty(opts)
    opts = struct();
end

fid = fopen(reportFilename, 'w');
if fid < 0
    warning('Could not open bin error report for writing: %s', reportFilename);
    return
end
cleanupObj = onCleanup(@() fclose(fid));

Param = local_opt(opts, 'Param', '');
minNID = local_opt(opts, 'minNID', NaN);
didRebin = local_opt(opts, 'didRebin', false);
rebinTolPct = local_opt(opts, 'rebinTolPct', NaN);
figName = local_opt(opts, 'figName', '');
reportModelLabel = local_opt(opts, 'reportModelLabel', '');
generatedBy = local_opt(opts, 'generatedBy', 'write_bin_error_report');

titleText = sprintf('Binned Prediction Error Report: %s', char(string(Param)));
fprintf(fid, '%s\n', titleText);
fprintf(fid, '%s\n\n', repmat('=', 1, numel(titleText)));
fprintf(fid, 'Generated: %s\n', char(datetime("now", "Format", "yyyy-MM-dd HH:mm:ss")));
fprintf(fid, 'Generated by: %s\n', char(string(generatedBy)));
if strlength(string(figName)) > 0
    fprintf(fid, 'Figure label: %s\n', char(string(figName)));
end
if ~isnan(double(minNID))
    fprintf(fid, 'Binning by %s minID=%d\n', char(string(Param)), minNID);
else
    fprintf(fid, 'Binning by %s\n', char(string(Param)));
end
if strlength(string(reportModelLabel)) > 0
    fprintf(fid, 'Binned group table model: %s\n', char(string(reportModelLabel)));
end
fprintf(fid, 'Adaptive rebinning used: %s\n', local_logical_to_text(didRebin));
if isfinite(double(rebinTolPct))
    fprintf(fid, 'Rebin tolerance percent: %.6g\n\n', rebinTolPct);
else
    fprintf(fid, '\n');
end

fprintf(fid, 'Model Error Across Iterations\n');
fprintf(fid, '-----------------------------\n');
fprintf(fid, 'MeanAbsPctError is averaged across included bins within each iteration, then summarized across iterations.\n\n');
if isempty(modelErrorSummaryTbl)
    fprintf(fid, 'No model error summary rows were available.\n\n');
else
    local_write_report_table(fid, modelErrorSummaryTbl);
end

fprintf(fid, 'Sorted Error By Bin\n');
fprintf(fid, '-------------------\n');
fprintf(fid, 'Rows are binned groups sorted from lowest to highest mean absolute percent error across all iterations.\n');
fprintf(fid, 'Only bins with N_ID > 1 are included in plots and reports.\n');
fprintf(fid, 'Bias is based on signed percent error averaged across all iterations.\n');
fprintf(fid, 'VA, Distance, and Elevation ranges are the ranges of the source rows in each bin.\n\n');

if isempty(reportTbl)
    fprintf(fid, 'No bin error rows were available.\n');
    return
end

local_write_report_table(fid, reportTbl);
end

function value = local_opt(opts, fieldName, defaultValue)
if isstruct(opts) && isfield(opts, fieldName) && ~isempty(opts.(fieldName))
    value = opts.(fieldName);
else
    value = defaultValue;
end
end

function local_write_report_table(fid, tbl)
if exist('write_plain_text_table', 'file') == 2
    write_plain_text_table(fid, tbl);
else
    dispText = evalc('disp(tbl)');
    fprintf(fid, '%s\n', regexprep(dispText, '<[^>]+>', ''));
end
end

function textValue = local_logical_to_text(value)
if value
    textValue = 'true';
else
    textValue = 'false';
end
end
