function statsTbl = write_latentDmoon_model_report(latentSummaryTbl, outFile, opts)
% write_latentDmoon_model_report Write summary statistics for latent-Dmoon fits.
%
% statsTbl = write_latentDmoon_model_report(latentSummaryTbl, outFile, opts)
%
% Reports the across-iteration mean, standard deviation, and 95% confidence
% interval for the estimated fixed-effect coefficients and fitted Dmoon.
%
% Inputs
%   latentSummaryTbl : table returned/stacked from PM_lme_latentDmoon.
%   outFile          : optional text report path.
%   opts             : optional struct with metadata fields:
%                      GeneratedBy, SourceCSV, FigureLabel, Notes, GroupTbl.
%
% Output
%   statsTbl         : table with Parameter, N, Mean, SD, CI95_Lower,
%                      and CI95_Upper.

if nargin < 2
    outFile = "";
end
if nargin < 3 || isempty(opts)
    opts = struct();
end
if ~istable(latentSummaryTbl) || isempty(latentSummaryTbl)
    error('latentSummaryTbl must be a non-empty table.');
end

statsTbl = local_build_stats_table(latentSummaryTbl);

if strlength(string(outFile)) == 0
    return;
end

[outDir,~,~] = fileparts(char(outFile));
if ~isempty(outDir) && ~exist(outDir, 'dir')
    mkdir(outDir);
end

fid = fopen(outFile, 'w');
if fid < 0
    error('Could not open report file for writing: %s', outFile);
end
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid, 'Latent Dmoon Model Report\n');
fprintf(fid, '==========================\n\n');
fprintf(fid, 'Generated: %s\n', char(datetime("now", "Format", "yyyy-MM-dd HH:mm:ss")));
fprintf(fid, 'Generated by: %s\n', local_opt_text(opts, 'GeneratedBy', 'write_latentDmoon_model_report'));
fprintf(fid, 'Source CSV: %s\n', local_opt_text(opts, 'SourceCSV', ''));
fprintf(fid, 'Figure label: %s\n', local_opt_text(opts, 'FigureLabel', ''));
fprintf(fid, 'Model: log2(PM) ~ log2(VA) + log2(D) + log2(1+|E|) + (1|ID)\n');
fprintf(fid, 'Moon distance: fitted by moon distance group, constrained to Dmoon > minimum distance bound.\n');
fprintf(fid, 'N fits: %d\n', height(latentSummaryTbl));
notes = local_opt_text(opts, 'Notes', '');
if strlength(string(notes)) > 0
    fprintf(fid, 'Notes: %s\n', notes);
end
fprintf(fid, '\n');

fprintf(fid, 'Across-Iteration Estimates\n');
fprintf(fid, '---------------------------\n');
fprintf(fid, 'CI95 is computed across cross-validation iterations using mean +/- t(0.975, N-1) * SEM.\n\n');
write_plain_text_table(fid, statsTbl);

if all(ismember(["AIC","BIC","LogLikelihood"], string(latentSummaryTbl.Properties.VariableNames)))
    fitTbl = local_build_stats_table(latentSummaryTbl, ...
        ["AIC","BIC","LogLikelihood"], ...
        ["AIC","BIC","LogLikelihood"]);
    fprintf(fid, 'Model Fit Across Iterations\n');
    fprintf(fid, '---------------------------\n');
    write_plain_text_table(fid, fitTbl);
end

groupTbl = local_opt_table(opts, 'GroupTbl');
if ~isempty(groupTbl)
    fprintf(fid, 'Dmoon Group Estimates Across Iterations\n');
    fprintf(fid, '---------------------------------------\n');
    fprintf(fid, 'Each row summarizes fitted Dmoon values for one moon distance group across cross-validation iterations.\n\n');
    write_plain_text_table(fid, local_group_stats_table(groupTbl));
end

end

function statsTbl = local_build_stats_table(tbl, varNames, labels)
if nargin < 2
    varNames = ["Intercept","VAe","De","Ee","DmoonMean_m","DmoonMean_m","DmoonMedian_m","DmoonMin_m","DmoonMax_m","DmoonNGroups","DmoonLowerBound_m"];
    labels = ["Intercept","VA exponent","Distance exponent","Elevation exponent","Mean Dmoon [m]","Mean Dmoon [km]","Median Dmoon [m]","Min Dmoon [m]","Max Dmoon [m]","N Dmoon groups","Dmoon lower bound [m]"];
    if ~ismember("DmoonMean_m", string(tbl.Properties.VariableNames)) && ismember("Dmoon_m", string(tbl.Properties.VariableNames))
        varNames(5:6) = ["Dmoon_m","Dmoon_m"];
    end
end

parameter = strings(numel(varNames), 1);
n = nan(numel(varNames), 1);
meanValue = nan(numel(varNames), 1);
sdValue = nan(numel(varNames), 1);
ciLower = nan(numel(varNames), 1);
ciUpper = nan(numel(varNames), 1);

for iVar = 1:numel(varNames)
    varName = varNames(iVar);
    parameter(iVar) = labels(iVar);
    if ~ismember(varName, string(tbl.Properties.VariableNames))
        continue;
    end

    values = double(tbl.(char(varName)));
    if contains(labels(iVar), "[km]")
        values = values / 1000;
    end
    values = values(isfinite(values));
    n(iVar) = numel(values);
    if isempty(values)
        continue;
    end
    meanValue(iVar) = mean(values, 'omitnan');
    sdValue(iVar) = std(values, 'omitnan');
    [ciLower(iVar), ciUpper(iVar)] = local_ci95(values);
end

statsTbl = table(parameter, n, meanValue, sdValue, ciLower, ciUpper, ...
    'VariableNames', {'Parameter','N','Mean','SD','CI95_Lower','CI95_Upper'});
end

function statsTbl = local_group_stats_table(groupTbl)
required = ["DmoonGroup","Dmoon_m"];
missing = setdiff(required, string(groupTbl.Properties.VariableNames));
if ~isempty(missing)
    statsTbl = table();
    return
end

[G, groupNames] = findgroups(string(groupTbl.DmoonGroup));
n = splitapply(@(x) sum(isfinite(x)), groupTbl.Dmoon_m, G);
meanD = splitapply(@(x) mean(x, 'omitnan'), groupTbl.Dmoon_m, G);
sdD = splitapply(@(x) std(x, 'omitnan'), groupTbl.Dmoon_m, G);
medianD = splitapply(@(x) median(x, 'omitnan'), groupTbl.Dmoon_m, G);
minD = splitapply(@(x) min(x, [], 'omitnan'), groupTbl.Dmoon_m, G);
maxD = splitapply(@(x) max(x, [], 'omitnan'), groupTbl.Dmoon_m, G);
ciL = nan(size(meanD));
ciU = nan(size(meanD));
for ii = 1:numel(groupNames)
    values = groupTbl.Dmoon_m(G == ii);
    [ciL(ii), ciU(ii)] = local_ci95(values);
end

statsTbl = table(groupNames, n, meanD, sdD, medianD, minD, maxD, ciL, ciU, ...
    'VariableNames', ["DmoonGroup","N","MeanDmoon_m","SDDmoon_m","MedianDmoon_m","MinDmoon_m","MaxDmoon_m","CI95_Lower_m","CI95_Upper_m"]);
statsTbl = sortrows(statsTbl, "DmoonGroup");
end

function [ciLower, ciUpper] = local_ci95(values)
values = values(isfinite(values));
n = numel(values);
if n < 2
    ciLower = NaN;
    ciUpper = NaN;
    return;
end
semValue = std(values, 'omitnan') / sqrt(n);
try
    tCrit = tinv(0.975, n - 1);
catch
    tCrit = 1.96;
end
meanValue = mean(values, 'omitnan');
ciLower = meanValue - tCrit * semValue;
ciUpper = meanValue + tCrit * semValue;
end

function value = local_opt_text(opts, fieldName, defaultValue)
if isstruct(opts) && isfield(opts, fieldName) && ~isempty(opts.(fieldName))
    value = char(string(opts.(fieldName)));
else
    value = char(string(defaultValue));
end
end

function value = local_opt_table(opts, fieldName)
if isstruct(opts) && isfield(opts, fieldName) && istable(opts.(fieldName)) && ~isempty(opts.(fieldName))
    value = opts.(fieldName);
else
    value = table();
end
end
