% Combined_lme_full_BoringBinocular_subject_intercepts
% Apply the fixed-effect slopes from lme_full saved by
% SMS_Fig3ac_CombinedQuadMoon_PM_angle_distance_elevation_071426 to the
% Boring Binocular data. Estimate one conditional intercept per Boring
% participant, then plot each participant's data and fitted elevation curve.

set(groot, 'defaultFigureVisible', 'on');
close all ; clear all;

modelFile = fullfile('/Users/kalanit/Projects/StanfordMoonStudy', ...
    'Figures', 'Fig3ac', ...
    ['combined_Perceptual_FullMoonDataProcessed090225_Perceptual_' ...
    'StanfordQuadStudyDataProcessed0420.mat']);
boringDir='/Users/kalanit/Projects/PerceptualMagnification/Paper/ExperimentalData/MoonExperiments/'
boringFile = fullfile( boringDir ,   'BoringDataProcessed_simple.csv');
ResultsDir = fullfile('/Users/kalanit/Projects/PerceptualMagnification/Paper/ExperimentalData/', 'PaperFigures', 'BoringData');
if ~exist(ResultsDir, 'dir')
    mkdir(ResultsDir);
end

%% Load the exact lme_full generated by the combined Moon-Quad analysis
if ~exist(modelFile, 'file')
    error('BoringCombinedLME:MissingModel', ...
        'Run SMS_Fig3ac_CombinedQuadMoon_PM_angle_distance_elevation_071426. Expected %s.', ...
        modelFile);
end
savedModel = load(modelFile, 'combinedLMEStore');
lme_full = savedModel.combinedLMEStore.Perceptual.absElevation;

coefficientNames = string(lme_full.Coefficients.Name);
interceptFixed = lme_full.Coefficients.Estimate( ...
    coefficientNames == "(Intercept)");
VAe = lme_full.Coefficients.Estimate( ...
    coefficientNames == "log2real_angle");
De = lme_full.Coefficients.Estimate( ...
    coefficientNames == "log2distance");
Ee = lme_full.Coefficients.Estimate( ...
    coefficientNames == "log2elevation");

%% Load and transform only the Boring Binocular data
boringData = readtable(boringFile);
binocularRows = strcmpi(strtrim(string(boringData.Task)), "Binocular");
boringData = boringData(binocularRows, :);

% The combined analysis converts Moon distance from km to meters and uses
% transform 2: log2(1 + abs(Elevation)). Match those units/transforms here.
boringData.Distance_m = 1000*(boringData.Distance);
boringData.log2ratio_visual_angle = ...
    log2(double(boringData.Ratio_Visual_Angle));
boringData.log2real_angle = log2(double(boringData.Real_Visual_Angle));
boringData.log2distance = log2(boringData.Distance_m);
boringData.log2elevation = log2(1 + abs(double(boringData.Elevation)));

validRows = all(isfinite([boringData.log2ratio_visual_angle, ...
    boringData.log2real_angle, boringData.log2distance, ...
    boringData.log2elevation]), 2);
boringData = boringData(validRows, :);

%% Estimate a conditional intercept for every Boring participant
participantIDs = unique(boringData.ID);
nParticipants = numel(participantIDs);
participantN = zeros(nParticipants, 1);
participantInitials = strings(nParticipants, 1);
estimatedIntercept = nan(nParticipants, 1);
meanLog2VisualAngle = nan(nParticipants, 1);
meanLog2Distance = nan(nParticipants, 1);

for participantIdx = 1:nParticipants
    participantRows = boringData.ID == participantIDs(participantIdx);
    participantN(participantIdx) = sum(participantRows);
    initialsForParticipant = unique(strtrim(string( ...
        boringData.Initials(participantRows))), 'stable');
    initialsForParticipant = initialsForParticipant( ...
        ~ismissing(initialsForParticipant) & strlength(initialsForParticipant) > 0);
    if ~isempty(initialsForParticipant)
        participantInitials(participantIdx) = initialsForParticipant(1);
    else
        participantInitials(participantIdx) = ...
            "ID " + string(participantIDs(participantIdx));
    end
    meanLog2VisualAngle(participantIdx) = mean( ...
        boringData.log2real_angle(participantRows), 'omitnan');
    meanLog2Distance(participantIdx) = mean( ...
        boringData.log2distance(participantRows), 'omitnan');

    fixedSlopeContribution = ...
        VAe .* boringData.log2real_angle(participantRows) + ...
        De .* boringData.log2distance(participantRows) + ...
        Ee .* boringData.log2elevation(participantRows);
    estimatedIntercept(participantIdx) = mean( ...
        boringData.log2ratio_visual_angle(participantRows) - ...
        fixedSlopeContribution, 'omitnan');
end

participantParameters = table(participantIDs, participantInitials, participantN, ...
    estimatedIntercept, estimatedIntercept - interceptFixed, ...
    2.^estimatedIntercept, meanLog2VisualAngle, meanLog2Distance, ...
    'VariableNames', {'ID', 'Initials', 'N', 'EstimatedIntercept_log2', ...
    'InterceptDeviationFromCombinedFixed', 'EstimatedIntercept_PM', ...
    'MeanLog2VisualAngle', 'MeanLog2Distance_m'});

%% Plot observations and subject-specific curves
participantColors = lines(nParticipants);
figureHandle = figure('Color', [1 1 1], 'Units', 'normalized', ...
    'Position', [0.12 0.08 0.6 0.8], ...
    'Name', 'Combined lme full applied to Boring Binocular participants');
axesHandle = axes(figureHandle);
hold(axesHandle, 'on');

maxElevation = max(abs(double(boringData.Elevation)));
elevationGrid = linspace(0, maxElevation, 250)';
log2ElevationGrid = log2(1 + elevationGrid);
legendHandles = gobjects(nParticipants, 1);
markerSize=100;
for participantIdx = 1:nParticipants
    participantRows = boringData.ID == participantIDs(participantIdx);
    participantColor = participantColors(participantIdx, :);
    legendHandles(participantIdx) = scatter(axesHandle, ...
        abs(double(boringData.Elevation(participantRows))), ...
        double(boringData.Ratio_Visual_Angle(participantRows)), markerSize, ...
        participantColor, 'o', 'filled', 'MarkerEdgeColor', 'none', ...
        'DisplayName', participantInitials(participantIdx));

    fittedLog2PM = estimatedIntercept(participantIdx) + ...
        VAe .* meanLog2VisualAngle(participantIdx) + ...
        De .* meanLog2Distance(participantIdx) + ...
        Ee .* log2ElevationGrid;
    plot(axesHandle, elevationGrid, 2.^fittedLog2PM, '-', ...
        'Color', participantColor, 'LineWidth', 2.5, ...
        'HandleVisibility', 'off');
end

yline(axesHandle, 1, '-', 'Color', [0.75 0.75 0.75], ...
    'LineWidth', 2, 'HandleVisibility', 'off');
xlabel(axesHandle, 'Moon Elevation (degrees)');
ylabel(axesHandle, 'Moon Perceptual Magnification');
set(axesHandle, 'FontName', 'Avenir', 'FontSize', 28, ...
    'Box', 'off', 'YScale', 'linear');
 xlim(axesHandle, [0 maxElevation]);
% ylim(axesHandle, [0, 1.05 .* max(double(boringData.Ratio_Visual_Angle))]);
legendHandle = legend(axesHandle, legendHandles, ...
    'Location', 'northeastoutside', 'FontSize', 24);
legendHandle.Box = 'off';
titlestr=sprintf('Predicting Boring, Holway & Taylor (1940,1942) from: \n PM=cVA^{%.2f}D^{%.2f}(1+|E|)^{%.2f}, c:observer-specific', VAe,De,Ee);

title(titlestr,'FontSize',20,'FontName','Avenir','FontWeight','normal')

outputStem = fullfile(ResultsDir, ...
    'Combined_lme_full_BoringBinocular_subject_intercepts');
exportgraphics(figureHandle, [outputStem '.png'], 'Resolution', 600);
print(figureHandle, [outputStem '.eps'], '-depsc', '-r600');
writetable(participantParameters, ...
    [outputStem '_participant_parameters.csv']);
save([outputStem '_analysis.mat'], 'lme_full', 'boringData', ...
    'participantParameters', 'participantColors', 'interceptFixed', ...
    'VAe', 'De', 'Ee', 'modelFile');

fprintf('Analyzed %d Binocular rows from %d Boring participants.\n', ...
    height(boringData), nParticipants);
fprintf('Saved figure: %s.png\n', outputStem);
fprintf('Saved participant parameters: %s_participant_parameters.csv\n', ...
    outputStem);
